config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
  
  authenticated :user do 
    root "welcome#home"
     resources :fruits
  end

  unauthenticated :user do 
    root "welcome#unregistered", as: :unauthenticated_root
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/fruit.rb
class Fruit < ApplicationRecord
  belongs_to :user
  validates :name,:color,:origin,:season,:price,presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :fruits
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/fruits_controller.rb
class FruitsController < ApplicationController
  before_action :set_fruit, only: %i[ show edit update destroy ]
  def index
    @fruits = current_user.fruits.all
  end
  def show
  end
  def new
    @fruit = Fruit.new
  end
  def edit
  end
  def create
    @fruit = current_user.fruits.new(fruit_params)

    respond_to do |format|
      if @fruit.save
        format.html { redirect_to root_path, notice: "Fruit was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @fruit.update(fruit_params)
        format.html { redirect_to root_path, notice: "Fruit was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @fruit.destroy!

    respond_to do |format|
      format.html { redirect_to root_path, notice: "Fruit was successfully destroyed." }
    end
  end

  private
    def set_fruit
      @fruit = Fruit.find(params[:id])
    end

    def fruit_params
      params.require(:fruit).permit(:name, :color, :origin, :season, :price)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def unregistered
  end

  def home
    @fruits = current_user.fruits.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fruits_helper.rb
module FruitsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
  def resource_name
    :user
  end

  def resource
    @user ||= User.new
  end
  
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/fruits/_form.html.haml
= form_for @fruit do |f|
  - if @fruit.errors.any?
    #error_explanation
      %h2= "#{pluralize(@fruit.errors.count, "error")} prohibited this fruit from being saved:"
      %ul
        - @fruit.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name,class:"form-control"
  .field
    = f.label :color
    = f.text_field :color,class:"form-control"
  .field
    = f.label :origin
    = f.text_field :origin,class:"form-control"
  .field
    = f.label :season
    = f.text_field :season,class:"form-control"
  .field
    = f.label :price
    = f.text_field :price,class:"form-control"
    %br/
  .actions
    = f.submit 'Save',class:"btn btn-primary"

app/views/fruits/_index.haml
%h1 Listing fruits
= link_to "Add fruit", new_fruit_path,class:"nav-link active",class:"btn btn-primary mt-3 mb-2"
%br/
%table.table
  %thead
    %tr
      %th Name
      %th Color
      %th Origin
      %th Season
      %th Price
      %th User
      %th
      %th
      %th

  %tbody
    - @fruits.each do |fruit|
      %tr
        %td= fruit.name
        %td= fruit.color
        %td= fruit.origin
        %td= fruit.season
        %td= fruit.price
        %td= fruit.user.email
        %td= link_to 'Show', fruit, class:"btn btn-success"
        %td= link_to 'Edit', edit_fruit_path(fruit),class:"btn btn-warning"
        %td= link_to 'Destroy', fruit, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } ,class:"btn btn-danger"

app/views/fruits/edit.html.haml
.row.justify-content-center
  .col-md-6.white

    %h1 Editing fruit

    = render 'form'

    = link_to 'Show', @fruit
    \|
    = link_to 'Back', fruits_path

app/views/fruits/index.html.haml
.row.justify-content-center
  .col-md-6.white
    = render "index"

app/views/fruits/new.html.haml
.row.justify-content-center
  .col-md-4.white
    %h1 New fruit

    = render 'form'

    = link_to 'Back', fruits_path

app/views/fruits/show.html.haml
.row.justify-content-center
  .col-md-6.white
    %p
      %b Name:
      = @fruit.name
    %p
      %b Color:
      = @fruit.color
    %p
      %b Origin:
      = @fruit.origin
    %p
      %b Season:
      = @fruit.season
    %p
      %b Price:
      = @fruit.price
    %p
      %b User:
      = @fruit.user.email

    = link_to 'Edit', edit_fruit_path(@fruit)
    \|
    = link_to 'Back', fruits_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fruits</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </head>

  <body class="purple">
    <p class="green white-text text-center " style="padding:10px;<%='display:none;' if notice.nil? %>" >
      <%=notice%> 
    </p>
    <p class="red white-text text-center " style="padding:10px;<%='display:none;' if alert.nil? %>" >
      <%=alert%> 
    </p>
    <%if user_signed_in? %>
      <%= render "partials/navigation"%>  
    <%end%>
    
    <div class="mt-5">
      <%= yield %>  
    </div>
    
  </body>
</html>

app/views/partials/_navigation.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  .container-fluid
    = link_to "Fruits", root_path,class:"navbar-brand"
    %button.navbar-toggler{"aria-controls" => "navbarNavAltMarkup", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarNavAltMarkup", "data-bs-toggle" => "collapse", type: "button"}
      %span.navbar-toggler-icon
    #navbarNavAltMarkup.collapse.navbar-collapse
      .navbar-nav
        = link_to "Log Out", destroy_user_session_path, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } , class:"nav-link active"
        

app/views/welcome/home.html.haml
.row.justify-content-center
  .col-md-6
    %h3 
      %strong.white-text= "Here, you can manage all information about your fruits" 

.row.justify-content-center
  .col-md-6.white
    
    =render "fruits/index"

app/views/welcome/unregistered.html.haml
.row.justify-content-center
  .col-md-3.white 
    = render "/devise/sessions/new"